
title: My Resume
url: 'kritsada12.github.io'
baseurl: '/PanelCV' #change it according to your repository name



# Profile information
yourname: Kritsada Phalarat  ## put your name
title: •	PHP – Intermediate •	Github – Intermediate •	HTML - Intermediate
  ## your title
location: 80/366 Village No.3, Kham Yai, Ubon Ratchathani, 34000

## Social Profiles
facebook: https://www.facebook.com/kritsada.phalarat  ## your facebook account url
twitter: -  ## your twitter account url
linkedin: -  ## your linkedin account url
dribbble:  - ## you dribbble account url
foursquare: -  ## your foursquare account url



# Update all the sections by editing the files inside _includes folder.
